server:
  port: 8080
 
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
    packages:
      trust-all: true  
  jms:
    pub-sub-domain: true 